apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-pushgateway-monitor
  namespace: monitoring
spec:
  endpoints:
  - path: '/metrics'
    port: http
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: pushgateway-chart
      app.kubernetes.io/name: prometheus-pushgateway
